### PR TITLE
fix(igx-ts-legacy): update igx ts legacy templates

### LINKED ISSUE #1516: Update igx-ts-legacy templates

### PR DESCRIPTION
**Pull request by Hristo313**
Update igx-ts-legacy templates

Closes #1516

### CODE REVIEW

File: packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { routes } from "../app-routing.module";
 
 @Component({
   selector: "nav-menu",
```
Comment (wnvko) [inline packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts:5]: we should add `standalone: false` for all components here.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
Comment (wnvko) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json:1]: Angular are adding now `"prettier": "^3.8.1"` and also are moving to `"vitest": "^4.0.8"`. Should we do this too now?

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.spec.json
Comment (wnvko) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.spec.json]: Angular now adds these comments to all `tsconfig` files
```json
/* To learn more about Typescript configuration file: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html. */
/* To learn more about Angular compiler options: https://angular.dev/reference/configs/angular-compiler-options. */
```

File: packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.ts
Comment (wnvko) [inline packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.ts:1]: Should we remove `component` from the path and class names everywhere?. If I run now `ng g c home` it will generate class named `Home` and files `home.html`, `home.scss`, `home.spec.ts` and `home.ts`. No `component` anywhere.

File: packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
Comment (wnvko) [inline packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json:1]: in `_base` we have `prettier` and it is gone here. Is this correct?

File: packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
Comment (wnvko) [inline packages/cli/templates/angular/ig-ts/projects/empty/files/package.json:1]: should we add `prettier` here too?

File: packages/cli/migrations/update-2/index.spec.ts
Comment (wnvko) [inline packages/cli/migrations/update-2/index.spec.ts:1]: I am not sure we need any changes in all these old migrations.

File: packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts (hunk 1 above)
Comment (damyanpetev) [reply packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts:5]: Oh, `ig-ts` project shouldn't be updated at all. IIRC it's slated for removal instead

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json:1]: Yes, it's updated

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.spec.json
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.spec.json]: Updated

File: packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json:1]: Fixed.

File: packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
Comment (Hristo313) [reply packages/cli/templates/angular/ig-ts/projects/empty/files/package.json:1]: Won't fix ig-ts templates

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json:1]: Vite will be added in other PR

File: packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.ts
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.ts:1]: Updated all components

File: packages/cli/migrations/update-2/index.spec.ts
Comment (Hristo313) [reply packages/cli/migrations/update-2/index.spec.ts:1]: Reverted

File: packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
Comment (Hristo313) [reply packages/cli/templates/angular/ig-ts/projects/empty/files/package.json:1]: Reverted the changes in ig-ts

File: packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts (hunk 1 above)
Comment (Hristo313) [reply packages/cli/templates/angular/ig-ts/projects/empty/files/src/app/shared/nav-menu.component.ts:5]: Reverted the changes in ig-ts

**Review by wnvko — APPROVED** [review]

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json [hunk 2]
```diff
@@ -11,37 +11,39 @@
...
+    "@angular/cli": "~21.2.1",
+    "@angular/compiler-cli": "~21.2.0",
+    "@eslint/js": "^10.0.1",
     "@types/jasmine": "~5.1.4",
-    "angular-eslint": "~21.2.0",
-    "eslint": "~9.39.1",
+    "angular-eslint": "~21.3.0",
+    "eslint": "^10.0.2",
     "igniteui-cli": "~<%=cliVersion%>",
+    "jsdom": "^28.0.0",
```
Comment (damyanpetev) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json]: That's probably for vitest (not in this PR) and I'd still consider running a browser (playwright) setup probably

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json
Comment (damyanpetev) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]: This isn't up to date from what I can see, some of those are defaults anyway (like `"forceConsistentCasingInFileNames": true` and `"declaration": false`), `sourceMap` is handled by the angular config and I think `downlevelIteration` simply wasn't updated in this when it was removed from the baseline

Comment (damyanpetev) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]:
```suggestion
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ES2022",
    "module": "preserve"
```
I'd only consider keeping `useDefineForClassFields`, but it should not be needed - that's something we still have in the library, but it shouldn't affect client apps.

Comment (damyanpetev) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]: Meh, GH messed up the suggestion preview or lines

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json [hunk 3]
```diff
@@ -37,5 +38,14 @@
         "optionalChainNotNullable": "suppress"
```
Comment (damyanpetev) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]: Would also see if this is needed still and would love to drop it as well, pretty sure it's also quite outdated at this point.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/src/main.ts
Comment (damyanpetev) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/src/main.ts]: Eh I thought this is to be removed, since it's not needed and controlled via the angular config

Comment (damyanpetev) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/src/main.ts]: And without that you can also probably drop the `production` prop from the environment and keep it 1:1 with the latest generated

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import { Component, signal } from '@angular/core';
+
+@Component({
+  selector: 'app-root',
+  templateUrl: './app.html',
+  standalone: false,
+  styleUrl: './app.scss'
+})
+export class App {
+  protected readonly title = signal('Home - IgniteUI for Angular');
```
Comment (damyanpetev) [inline packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app.ts:10]: Not entirely certain we want to also update all the modules source with signals, but sure; Also not really used, in the base at least.

That also sort of raises the question if we should updating all the naming for legacy too, but for consistency at least I suppose.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json (hunk 2 above)
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json]: Remove the jsdom and playwright will be added with the changes for vite in other PR.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]: Updated.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json (hunk 3 above)
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json]: Yes, it's removed now.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/src/main.ts
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/src/main.ts]: Updated.

File: packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app.ts (hunk 4 above)
Comment (Hristo313) [reply packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app.ts:10]: Updated in the base templates
