### PR TITLE
fix: Add custom parameters to Google Analytics

### LINKED ISSUE #282: Generate analytics information for the chosen framework
### Description  
We should have separate analytics for the framework end user has chosen while using IgniteUI CLI.

### PR DESCRIPTION
**Pull request by wnvko**
Closes #282

### CODE REVIEW

File: lib/commands/config.ts [hunk 1]
```diff
@@ -76,6 +76,14 @@ const command = {
 			return;
 		}
 		const config = ProjectConfig.getConfig(argv.global);
+
+		GoogleAnalytics.post({
+			cd: "Config",
```
Comment (damyanpetev) [inline lib/commands/config.ts]: "Config" as screen view alone isn't too meaningful as you can't tell apart the get from the set.

File: lib/commands/test.ts [hunk 2]
```diff
@@ -21,15 +21,28 @@ const command = {
...
 		}
 
-		command.test(argv);
-	},
-	async test(argv) {
 		const projConfig = ProjectConfig.getConfig().project;
+
+		if (!argv.skipAnalytics) {
+			GoogleAnalytics.post({
+				cd: "Build",
```
Comment (damyanpetev) [inline lib/commands/test.ts]: Test?

File: lib/commands/config.ts (hunk 1 above)
Comment (damyanpetev) [reply lib/commands/config.ts]: I guess the same applies to generate + template, though I'm ot sure what param can be used to specify sub command and args easily. Maybe further details can be attached via events as far as I can tell or just separate screen names if nothing else works.
