### PR TITLE
fix(package-manager): manually update pckgJSON when adding packages

### LINKED ISSUE #751: Missing module when installing licensed package in project with charts
### Description  
I am installing the licensed package and adding template with charts. After installation is over an error is shown:

```
ERROR in The target entry-point "igniteui-angular-charts" has missing dependencies:
 - igniteui-angular-core
```

- Ignite UI CLI version: 5.1.0-beta.3
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Call `ig new` command.
2. Choose name, project template and theme for your application. I chose `empty project` and `default` theme.
3. Choose add scenario and add `FinTech Grid`.
4. Choose complete and run.
5. When asked confirm you would like to upgrade to licensed feed and input your credentials.

### Result  
Above mentioned error shows in the console after installation competes and the project does not start.

### Expected result  
All necessary packages should be installed correctly and project should run with no errors.

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Co-authored-by: Damyan Petev <damyan.petev@gmail.com>

Closes #751.  

Additional information related to this pull request:

`npm install` fails to update package.json when there are other changes. When calling `queuePackage`, manually update package.json

### CODE REVIEW

File: packages/core/packages/PackageManager.ts [hunk 1]
```diff
@@ -153,11 +160,17 @@ export class PackageManager {
 	}
 
 	public static async queuePackage(packageName: string, verbose = false) {
-		const command = this.getInstallCommand(this.getManager(), packageName);
-		const packName = packageName.split(/@[^\/]+$/)[0];
-		if (this.getPackageJSON().dependencies[packName] || this.installQueue.find(x => x["packageName"] === packName)) {
+		const command = this.getInstallCommand(this.getManager(), packageName).replace("--save", "--no-save");
```
Comment (wnvko) [inline packages/core/packages/PackageManager.ts:163]: I would go with pass optional parameters to `getInstallCommand` something like:
```
private static getInstallCommand(managerCommand: string, packageName: string, quiet=true, save=true): string
```
or as option:
```
private static getInstallCommand(managerCommand: string, packageName: string, options: InstallCommandOptions): string

interface InstallCommandOptions {
	quiet: boolean;
	save: boolean;
}
```
