### PR TITLE
indentation across igr-ts projects

### LINKED ISSUE #1219: Inconsistent indentation across generated project
### Description  
Indentation is not same in all the files.

- Ignite UI CLI version: 13.1.10
- Framework: React
- Project type: ig-ts

### Steps to reproduce  

1. Create react TS project using empty template.
2. Install npm packages.
3. Observe the indentation in generated files:
  - `home.tsx`, `app.test.tsx` and `ignite-ui-cli.json` have four spaces for indentation.
  - `style.module.css`, `app-route.tsx`, `.eslintrc.cjs`, `index.html`, `package.json`, `styles.css` and `tsconfig.json` have two spaces for indentation.
  - `app.tsx`, `style-utils.ts` and `vite.config.ts` have tabs for indentation.
  - `main.tsx` has mixed tabs and spaces for indentation.

### Result  
mixed indentation across the files in generated project as well as mixed indentation in some files.

### Expected result  
Indentation in all the files in generated project should follow same rule.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #1219   

use 2 spaces for indentation across all react igr-ts templates/components

### CODE REVIEW

**Review by gedinakova — CHANGES_REQUESTED** [review]
The only place remaining is the return statement in main.tsx: 
`Number.isNaN = Number.isNaN || function(value) {
    return value !== value;
}`

File: packages/cli/templates/react/igr-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.tsx [hunk 1]
```diff
@@ -6,54 +6,54 @@ IgrLinearGaugeModule.register();
 
 export default function $(ClassName)() {
     const title = 'Linear Gauge';
```
Comment (wnvko) [inline packages/cli/templates/react/igr-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.tsx:8]: from line 8th to line 58th there is two extra spaces.

**Review by wnvko — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]
