### PR TITLE
fix: change the regex to allow single letter name

### LINKED ISSUE #173: Allow names with just one letter and error fix message
- [x] 1. Allow project and template names with just one letter

**Current State**

> ? Name your component: a
> Name 'a' is not valid. Template names should start with a letter and can also contain numbers, dashes and spaces.> 

**Expected Result**
To create a component named with just one letter.

- [x] 2. Remove template from the message to avoid confusion and fit all scenarios (project/view/component etc) .

**Current State**

> ? Name your **component**: 1
> Name '1' is not valid. **Template** names should start with a letter and can also contain numbers, dashes and spaces.

**Expected Result**

> ? Name your component: 1
> Name '1' is not valid. Names should start with a letter and can also contain numbers, dashes and spaces.

### PR DESCRIPTION
**Pull request by wnvko**
Closes #173

cli.ts - reordering the commands to show correctly in the help
for all commands change the description as discussed with UX
fix all failing tests

### CODE REVIEW

File: lib/commands/generate.ts [hunk 1]
```diff
@@ -7,15 +7,15 @@ import { default as config } from "./config";
 const command = {
 	aliases: ["g"],
 	command: "generate",
-	desc: "Generates new project",
+	desc: "generates custom template",
```
Comment (damyanpetev) [inline lib/commands/generate.ts]: I guess this can stay for now, though `generate` can later on be extended beyond just custom templates

File: lib/commands/new.ts [hunk 2]
```diff
@@ -99,6 +99,12 @@ command = {
 		if (!argv["skip-git"] && !ProjectConfig.getConfig().skipGit) {
 			Util.gitInit(process.cwd(), argv.name);
 		}
+
+		Util.log("");
+		Util.log("Next Steps:");
```
Comment (damyanpetev) [inline lib/commands/new.ts]: 🙌
