### PR TITLE
fix(new, schematics): No prompts when "name" is provided

### LINKED ISSUE #595: ng-new schematic should be able to run without prompts, respect interactive
### Description  
If enough/all parameters are provided in the command or interactive~/defaults~ flags are used the command should be able to run without going through prompts.

- Ignite UI CLI version: 5.x.x
- Framework: Angular

### Steps to reproduce  

For example run 
```bash
 ng new newProject --collection="@igniteui/angular-schematics" --template=side-nav --theme=custom
```
or
```bash
ng new newProject --collection="@igniteui/angular-schematics" --no-interactive
```

### Result  
Regardless what you provide as as options, the new schematics always run through the step by step prompt.

### Expected result  
Prompts should not be displayed if the option is provided or are explicitly disabled.

### PR DESCRIPTION
**Pull request by dafo**
Closes #595.

### CODE REVIEW

**Comment by dafo** [comment]
Need to fix the test.  However, the change can be reviewed.

File: packages/ng-schematics/src/ng-new/index.ts [hunk 1]
```diff
@@ -34,11 +34,15 @@ export function newProject(options: OptionsSchema): Rule {
...
+		let nameProvided: boolean = false;
 
 		return chain([
 			(tree: Tree, _context: IgxSchematicContext): Observable<Tree> => {
 				return defer(async () => {
+					if (options.name) {
+						nameProvided = true;
+					}
+
 					if (!options.name || !prompt.nameIsValid(options.name)) {
```
Comment (ViktorSlavov) [inline packages/ng-schematics/src/ng-new/index.ts]: Not sure how this should behave if the provided name is not a valid one. With the current logic, if we pass an invalid name (e.g. `1111`), `nameProvided` will be set to `true` and the schematic will skip the `chooseActionLoop` part.

In the main cli, if an invalid name is provided, the process exits w/ an error message (defined in [new.ts](https://github.com/IgniteUI/igniteui-cli/blob/vNext/packages/cli/lib/commands/new.ts#L74))

File: packages/ng-schematics/src/ng-new/index.ts [hunk 2]
```diff
@@ -49,31 +53,20 @@ export function newProject(options: OptionsSchema): Rule {
...
-					if (!options.theme) {
-						options.theme = await prompt.getTheme(projLibrary);
-					}
-
 					if (options.theme && projLibrary.themes.indexOf(options.theme) === -1) {
 						throw new SchematicsException(`Theme not supported`);
 					}
+					const theme = options.theme || projLibrary.themes[0];
+					const projectTemplate = options.template || projLibrary.projectIds[0];
+					Util.log(`Project Name: ${options.name}, theme ${theme}`);
```
Comment (damyanpetev) [inline packages/ng-schematics/src/ng-new/index.ts]: This can move after the project template check

File: packages/ng-schematics/src/ng-new/index.ts [hunk 3]
```diff
@@ -148,7 +141,7 @@ export function newProject(options: OptionsSchema): Rule {
 					installChain.push(gitTask);
 				}
 
-				if (!options.skipInstall && !allOptionsProvided) {
+				if (!options.skipInstall) {
```
Comment (damyanpetev) [inline packages/ng-schematics/src/ng-new/index.ts]: This should still check for name provided. If you haven't been through the choose action loop, we shouldn't start the project as well

File: packages/ng-schematics/src/ng-new/index.ts (hunk 1 above)
Comment (dafo) [reply packages/ng-schematics/src/ng-new/index.ts]: I think it is best to let the customer know the provided name is not valid and prompt him to provide a valid name. After a valid name is provided, we will show the Actions loop prompt.

Comment (dafo) [reply packages/ng-schematics/src/ng-new/index.ts]: We have discussed it with @ViktorSlavov  and agreed it should exit the process as it may be invoked by a script and would never execute the prompt.

File: packages/ng-schematics/src/ng-new/index.ts [hunk 4]
```diff
@@ -47,43 +62,34 @@ export function newProject(options: OptionsSchema): Rule {
 							default: Util.getAvailableName(defaultProjName, true),
 							validate: prompt.nameIsValid
 						});
-					}
-
-					if (options.name && options.template && options.theme) {
-						allOptionsProvided = true;
+						nameProvided = false;
```
Comment (damyanpetev) [inline packages/ng-schematics/src/ng-new/index.ts]: This line is not even needed, it's false by default, right?
