### PR TITLE
test: Failing test for issue #148 fix

### LINKED ISSUE #148: ig ng cli produces bad class, module names when '-' used
## Description
When adding components through the cli to an IG nG project, if hyphens (-) are used (which follows recommendation by Google, see https://angular.io/tutorial) within the component name, errors occur in the generated code.

## Steps to Reproduce
1. `ig new test-project --framework=angular`
2. `cd test-project`
3. `ig add grid global-search-grid`

## Result
1. Check `global-search-grid.component.ts`. result:
`export class Global-search-gridComponent implements OnInit {`
hyphens not allowed in the class name
2. Check `app.module.ts`. result:
`import { Global } from "./global-search-grid/global-search-grid.component";`
no such class generated
`	declarations: [
		AppComponent,
		HomeComponent,
		Global
	],`
3. check `app-routing.module.ts` result:
`import { Global } from "./global-search-grid/global-search-grid.component";`

## Expected Result
Class should automagically generate as GlobalSearchGrid, as per nG team recommendation.

### PR DESCRIPTION
**Pull request by wnvko**
Closes #148

### CODE REVIEW

File: spec/unit/Util-spec.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import { Util } from "../../lib/Util";
+
+describe("Unit - Util", () => {
+	it("className should replace dashes and empty spaces", async done => {
+		const projectNames = [
```
Comment (damyanpetev) [inline spec/unit/Util-spec.ts]: 👍
