### PR TITLE
Prompt for template and theme if no name provided

### LINKED ISSUE #622: ng-new schematic should prompt for theme and template if no name is provided
### Description  
 If not providing a name to the ng new command you should go through all prompts.

Ignite UI CLI version: 5.x.x
Framework: Angular

### Steps to reproduce  

1. Run `ng new --collection="@igniteui/angular-schematics"`

### Result  
You are prompted for a name only. Then you enter the loop. 

### Expected result  
You are prompted for template and theme before reaching the loop.

### PR DESCRIPTION
**Pull request by dafo**
Closes #622.

### CODE REVIEW

File: packages/ng-schematics/src/ng-new/index_spec.ts [hunk 1]
```diff
@@ -26,6 +26,10 @@ describe("igniteui-angular-schematics", () => {
 			.and.returnValue(Promise.resolve(true)),
 			getProjectLibrary: spyOn(SchematicsPromptSession.prototype, "getProjectLibrary")
 			.and.returnValue((Promise.resolve(mockLibrary))),
+			getProjectTemplate: spyOn(SchematicsPromptSession.prototype, "getProjectTemplate")
+			.and.returnValue(Promise.resolve("empty-page")),
```
Comment (ViktorSlavov) [inline packages/ng-schematics/src/ng-new/index_spec.ts]: This might fail, because the name of the empty template was was changed to `'empty'` w/ this PR #623 .

Comment (dafo) [reply packages/ng-schematics/src/ng-new/index_spec.ts]: It won`t fail as the projectIds are mocked:
`projectIds: ["empty-page"]`
